### ISSUE TITLE
Strategy Executor panics on invalid target step

### ISSUE THREAD

**Issue by juliogreff** [bookingcom/shipper#262]
Here's some logs:

```
E0121 14:49:10.142092       1 runtime.go:73] Observed a panic: "index out of range" (runtime error: index out of range)                                                                                 [10/462622]
goroutine 4491 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1419160, 0x240d5b0)
        /shipper/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /shipper/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x1419160, 0x240d5b0)
        /usr/lib64/go/src/runtime/panic.go:522 +0x1b5
github.com/bookingcom/shipper/pkg/controller/release.genCapacityEnforcer.func1(0xc03f78faa0, 0xc0530a9020, 0x10, 0x10, 0xc03fcbac20, 0x18, 0x18, 0xc00049b180, 0x7f5d20405b28)
        /shipper/pkg/controller/release/strategy_executor.go:124 +0x808
github.com/bookingcom/shipper/pkg/controller/release.(*Pipeline).Process(0xc00cc6f3c8, 0xc03f78faa0, 0xc0530a9020, 0x1, 0x2, 0xc03fcbac20, 0x1, 0x2, 0x0, 0x495b01)
        /shipper/pkg/controller/release/strategy_executor.go:53 +0x10a
github.com/bookingcom/shipper/pkg/controller/release.(*StrategyExecutor).Execute(0xc03f78faa0, 0xc03f78faa0, 0xc03f78fa80, 0x0, 0x0, 0xc048623380, 0x0, 0x0, 0x7f5d20405b28, 0x0)
        /shipper/pkg/controller/release/strategy_executor.go:340 +0x206
github.com/bookingcom/shipper/pkg/controller/release.(*Controller).ensureReleaseState(0xc0002469a0, 0xc03f78f8c0, 0x1, 0x1, 0x2, 0xc03f78f8e0, 0x1, 0x2, 0x0, 0x0, ...)
        /shipper/pkg/controller/release/release_controller.go:491 +0x139
github.com/bookingcom/shipper/pkg/controller/release.(*Controller).syncOneReleaseHandler(0xc0002469a0, 0xc02e59d4c0, 0x1e, 0x0, 0x0)
        /shipper/pkg/controller/release/release_controller.go:360 +0xf2a
github.com/bookingcom/shipper/pkg/controller/release.(*Controller).processNextReleaseWorkItem(0xc0002469a0, 0xc031c6d700)
        /shipper/pkg/controller/release/release_controller.go:233 +0x109
github.com/bookingcom/shipper/pkg/controller/release.(*Controller).runReleaseWorker(0xc0002469a0)
        /shipper/pkg/controller/release/release_controller.go:206 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00a832270)
        /shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00a832270, 0x3b9aca00, 0x0, 0x1, 0xc0000d4120)
        /shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00a832270, 0x3b9aca00, 0xc0000d4120)
        /shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/bookingcom/shipper/pkg/controller/release.(*Controller).Run
        /shipper/pkg/controller/release/release_controller.go:197 +0x241
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range
```

It appears we do validate against an invalid target step for the current release being inspected, but we don't do so for the successor, causing the panic.

**Comment by juliogreff** [comment]
Closed by #264
