### ISSUE TITLE
Runtime panic caused by a no-checksum annotation on a secret object

### ISSUE THREAD

**Issue by icanhazbroccoli** [bookingcom/shipper#293]
While creating a new cluster, we missed the checksum annotation in it's secret and this caused a runtime panic:

```
E0305 15:47:10.209222       1 runtime.go:71] Observed a panic: Secret "foo-bar-baz" doesn't have a checksum annotation. this should be checked before calling 'create'
goroutine 501 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1356f40, 0xc0a3081be0)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x1356f40, 0xc0a3081be0)
	/usr/lib64/go/src/runtime/panic.go:679 +0x1b2
github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).create(0xc0001c0280, 0xc0e7260000, 0xc1423de3c0, 0xc1423de3c0, 0x0)
	/shipper/pkg/clusterclientstore/store.go:263 +0x7b2
github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).syncCluster(0xc0001c0280, 0xc12c394360, 0x22, 0xc12be33a10, 0xc0007be800)
	/shipper/pkg/clusterclientstore/store.go:195 +0x7ac
github.com/bookingcom/shipper/pkg/clusterclientstore.processNextWorkItem(0x17ca520, 0xc0002302e0, 0xc00116ee38, 0x0)
	/shipper/pkg/clusterclientstore/queue.go:118 +0x112
github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).clusterWorker(0xc0001c0280)
	/shipper/pkg/clusterclientstore/queue.go:17 +0x5d
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00091e3c0)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00091e3c0, 0x3b9aca00, 0x0, 0x1, 0xc0001d0000)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00091e3c0, 0x3b9aca00, 0xc0001d0000)



	/shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).Run
	/shipper/pkg/clusterclientstore/store.go:103 +0x3de
panic: Secret "foo-bar-baz" doesn't have a checksum annotation. this should be checked before calling 'create' [recovered]
	panic: Secret "foo-bar-baz" doesn't have a checksum annotation. this should be checked before calling 'create'

goroutine 501 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1356f40, 0xc0a3081be0)
	/usr/lib64/go/src/runtime/panic.go:679 +0x1b2
github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).create(0xc0001c0280, 0xc0e7260000, 0xc1423de3c0, 0xc1423de3c0, 0x0)
	/shipper/pkg/clusterclientstore/store.go:263 +0x7b2
github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).syncCluster(0xc0001c0280, 0xc12c394360, 0x22, 0xc12be33a10, 0xc0007be800)
	/shipper/pkg/clusterclientstore/store.go:195 +0x7ac
github.com/bookingcom/shipper/pkg/clusterclientstore.processNextWorkItem(0x17ca520, 0xc0002302e0, 0xc00116ee38, 0x0)
	/shipper/pkg/clusterclientstore/queue.go:118 +0x112
github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).clusterWorker(0xc0001c0280)
	/shipper/pkg/clusterclientstore/queue.go:17 +0x5d
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00091e3c0)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00091e3c0, 0x3b9aca00, 0x0, 0x1, 0xc0001d0000)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00091e3c0, 0x3b9aca00, 0xc0001d0000)
	/shipper/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/bookingcom/shipper/pkg/clusterclientstore.(*Store).Run
	/shipper/pkg/clusterclientstore/store.go:103 +0x3de
rpc error: code = Unknown desc = Error: No such container: c5181c73e5a8181e8fa5a11f81b8b04cab55732766a71176aec6f4bcbbe41405
```

**Comment by kanatohodets** [comment]
I honestly don't remember why we didn't have Shipper itself hash the secret to see if it needed to rebuild the client. Probably premature optimization. That would remove the need for this annotation entirely.

**Comment by kanatohodets** [comment]
Also, just to record here what we discussed on chat -- there's an bug because `syncCluster` doesn't check for the annotation and throw an error if it is missing, while `syncSecret` does.
